interhuman:
    NAME: interhuman
    DATA_ROOT: ./data/InterHuman
    MOTION_REP: global
    MODE: train
    CACHE: True

interhuman_val:
    NAME: interhuman
    DATA_ROOT: ./data/InterHuman
    MOTION_REP: global
    MODE: val
    CACHE: True

interhuman_test:
    NAME: interhuman
    DATA_ROOT: ./data/InterHuman
    MOTION_REP: global
    MODE: test
    CACHE: True
